<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>7.0.2</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>library-crmclient</artifactId>
    <version>2.0.5-SNAPSHOT</version>
    <name>Library CRM Client</name>
    <description>CRM Client library</description>
    
    <repositories>
        <repository>
            <id>luteceSnapshot</id>
            <name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
	
    <dependencies>
        <!-- Commons -->
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>${commons.lang.version}</version>
        </dependency>
        <!-- @Inject API -->
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>${javax.inject.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-httpaccess</artifactId>
            <version>[2.2.9,3.9.9)</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[3.0.0,7.9.9)</version>
            <type>lutece-core</type>
        </dependency>
    </dependencies>
    
    <properties>
        <jiraProjectName>LIBRARYCRMCLIENT</jiraProjectName>
        <jiraComponentId>10680</jiraComponentId>
        <sonar.host.url>http://dev.lutece.paris.fr/sonar</sonar.host.url>
        <javax.inject.version>1</javax.inject.version>
        <commons.lang.version>2.3</commons.lang.version>
    </properties>
	
    <scm>
        <connection>scm:git:https://github.com/lutece-secteur-public/gru-library-crmclient.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-secteur-public/gru-library-crmclient.git</developerConnection>
        <url>https://github.com/lutece-secteur-public/gru-library-crmclient.git</url>
      <tag>HEAD</tag>
  </scm>
    
</project>